[en]
    languageName = 'English'
    title = 'OpenStreetMap Belgium'
[fr]
    languageName = 'Français'
    title = 'OpenStreetMap Belgique'
[nl]
    languageName = 'Nederlands'
    title = 'OpenStreetMap België'
[de]
    languageName = 'Deutsch'
    title = 'OpenStreetMap Belgien'
    disabled = true
