baseURL = 'https://openstreetmap.be/'
defaultContentLanguage = 'en'
enableEmoji = true
summaryLength = 50

[frontmatter]
  date = [':filename', ':default']

[markup.goldmark.parser.attribute]
  block = true