---
name: Lint

on:
  push:
  pull_request:

jobs:

  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actionshub/markdownlint@main

  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-hub/stylelint@master
        env:
          PATTERN: "assets/css/input.css"